import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { classNames } from "./utils/appearance";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="icon"
        type="image/png"
        href="%PUBLIC_URL%/favicon-96x96.png"
        sizes="96x96"
      />
      <link rel="icon" type="image/svg+xml" href="%PUBLIC_URL%/favicon.svg" />
      <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="%PUBLIC_URL%/apple-touch-icon.png"
      />
      <meta name="apple-mobile-web-app-title" content="MyWebSite" />
      <link rel="manifest" href="%PUBLIC_URL%/site.webmanifest" />

      <body
        className={classNames(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          "flex flex-col justify-between"
        )}
      >
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
